// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsbWkcAQpArw09hGytPZUgLNp-Qlo4og4',
    appId: '1:27914400094:web:d98f604c228c1e17ba1fcf',
    messagingSenderId: '27914400094',
    projectId: 'healthypet-18aa1',
    authDomain: 'healthypet-18aa1.firebaseapp.com',
    storageBucket: 'healthypet-18aa1.appspot.com',
    measurementId: 'G-584EVBLFNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUKMGSDd_1SKXF8lXk87SEn5rd-ZB9IRA',
    appId: '1:27914400094:android:608ad8a4c9ac0a0bba1fcf',
    messagingSenderId: '27914400094',
    projectId: 'healthypet-18aa1',
    storageBucket: 'healthypet-18aa1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDokcRPV1fXJUD6gbd6tPicMIEFOhzaEMA',
    appId: '1:27914400094:ios:04b495e4eca22f75ba1fcf',
    messagingSenderId: '27914400094',
    projectId: 'healthypet-18aa1',
    storageBucket: 'healthypet-18aa1.appspot.com',
    iosBundleId: 'com.example.healthypet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDokcRPV1fXJUD6gbd6tPicMIEFOhzaEMA',
    appId: '1:27914400094:ios:04b495e4eca22f75ba1fcf',
    messagingSenderId: '27914400094',
    projectId: 'healthypet-18aa1',
    storageBucket: 'healthypet-18aa1.appspot.com',
    iosBundleId: 'com.example.healthypet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsbWkcAQpArw09hGytPZUgLNp-Qlo4og4',
    appId: '1:27914400094:web:1c6c691a0440f442ba1fcf',
    messagingSenderId: '27914400094',
    projectId: 'healthypet-18aa1',
    authDomain: 'healthypet-18aa1.firebaseapp.com',
    storageBucket: 'healthypet-18aa1.appspot.com',
    measurementId: 'G-RF82X3NP8H',
  );
}
